id: P311436BC
initial_creation_type: ocr
source_metadata:
  volumes:
    e7454e71517c40a4bce1bb73a155bf57:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      volume_number: 47
